export const runtime = "nodejs";

import PDFDocument from "pdfkit";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

const GREEN = "#16a34a";
const GREEN_DARK = "#15803d";
const GREY_TEXT = "#78716c";
const BODY_TEXT = "#1c1917";
const BORDER = "#e7e5e4";
const ROW_ALT = "#f9fafb";
const HEADER_BG = "#f0fdf4";

// Strip emoji and markdown symbols for plain PDF text
function clean(str: string): string {
  return str
    .replace(/\*\*(.*?)\*\*/g, "$1")       // bold
    .replace(/\*(.*?)\*/g, "$1")            // italic
    .replace(/✅/g, "OK")
    .replace(/⚠️/g, "(!)")
    .replace(/❌/g, "(X)")
    .replace(/[^\x00-\x7F]/g, "")          // strip remaining non-ASCII (emoji etc.)
    .trim();
}

function buildPDF(content: string, title: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const ml = doc.page.margins.left;
    const mr = doc.page.margins.right;
    const PAGE_W = doc.page.width - ml - mr;

    // ── Title block ────────────────────────────────────────────────
    doc.font("Helvetica-Bold").fontSize(22).fillColor(GREEN)
      .text(title, { align: "center" });
    doc.moveDown(0.3);
    doc.font("Helvetica").fontSize(9).fillColor(GREY_TEXT)
      .text(
        `Generated by Nora · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
        { align: "center" }
      );
    doc.moveDown(1.2);

    // ── Parser ─────────────────────────────────────────────────────
    const lines = content.split("\n");
    let tableRows: string[][] = [];
    let inTable = false;

    const flushTable = () => {
      if (tableRows.length === 0) { inTable = false; return; }

      // Drop separator rows (e.g. |---|---|)
      const rows = tableRows.filter(
        (r) => !r.every((c) => /^[-: ]+$/.test(c))
      );
      tableRows = [];
      inTable = false;
      if (rows.length === 0) return;

      const numCols = Math.max(...rows.map((r) => r.length));
      const COL_W = PAGE_W / numCols;
      const ROW_H = 16;
      const PAD = 3;
      const FONT_SIZE = 8;

      rows.forEach((row, ri) => {
        const isHeader = ri === 0;

        // Page break check
        if (doc.y + ROW_H > doc.page.height - doc.page.margins.bottom - 10) {
          doc.addPage();
        }

        const rowY = doc.y;

        // Row background
        doc.save()
          .rect(ml, rowY, PAGE_W, ROW_H)
          .fill(isHeader ? HEADER_BG : ri % 2 === 0 ? "#ffffff" : ROW_ALT)
          .restore();

        // Cell borders (top line)
        doc.save()
          .moveTo(ml, rowY).lineTo(ml + PAGE_W, rowY)
          .strokeColor(BORDER).lineWidth(0.5).stroke()
          .restore();

        // Cell text
        row.forEach((cell, ci) => {
          const x = ml + ci * COL_W + PAD;
          doc
            .font(isHeader ? "Helvetica-Bold" : "Helvetica")
            .fontSize(FONT_SIZE)
            .fillColor(BODY_TEXT)
            .text(clean(cell), x, rowY + PAD, {
              width: COL_W - PAD * 2,
              lineBreak: false,
              ellipsis: true,
            });
        });

        // Advance cursor to next row
        doc.text("", ml, rowY + ROW_H);
      });

      // Bottom border
      doc.save()
        .moveTo(ml, doc.y).lineTo(ml + PAGE_W, doc.y)
        .strokeColor(BORDER).lineWidth(0.5).stroke()
        .restore();

      doc.moveDown(0.8);
    };

    for (const line of lines) {
      const t = line.trim();

      // Table row
      if (t.startsWith("|")) {
        inTable = true;
        const cells = t.split("|").slice(1, -1).map((c) => c.trim());
        tableRows.push(cells);
        continue;
      }

      if (inTable) flushTable();

      if (t === "") {
        doc.moveDown(0.3);
      } else if (t.startsWith("# ")) {
        doc.moveDown(0.4);
        doc.font("Helvetica-Bold").fontSize(17).fillColor(GREEN)
          .text(clean(t.slice(2)));
        doc.moveDown(0.3);
      } else if (t.startsWith("## ")) {
        doc.moveDown(0.5);
        // Section rule
        doc.save()
          .moveTo(ml, doc.y).lineTo(ml + PAGE_W, doc.y)
          .strokeColor(GREEN).lineWidth(1).stroke()
          .restore();
        doc.moveDown(0.2);
        doc.font("Helvetica-Bold").fontSize(14).fillColor(GREEN)
          .text(clean(t.slice(3)));
        doc.moveDown(0.3);
      } else if (t.startsWith("### ")) {
        doc.moveDown(0.3);
        doc.font("Helvetica-Bold").fontSize(11).fillColor(GREEN_DARK)
          .text(clean(t.slice(4)));
        doc.moveDown(0.2);
      } else if (t === "---") {
        doc.save()
          .moveTo(ml, doc.y).lineTo(ml + PAGE_W, doc.y)
          .strokeColor(BORDER).lineWidth(0.5).stroke()
          .restore();
        doc.moveDown(0.5);
      } else if (t.startsWith("- ") || t.startsWith("* ")) {
        doc.font("Helvetica").fontSize(10).fillColor(BODY_TEXT)
          .text(`• ${clean(t.slice(2))}`, { indent: 12 });
        doc.moveDown(0.1);
      } else {
        doc.font("Helvetica").fontSize(10).fillColor(BODY_TEXT)
          .text(clean(t));
        doc.moveDown(0.15);
      }
    }

    if (inTable) flushTable();

    doc.end();
  });
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) return new Response("Unauthorized", { status: 401 });

  const { id } = await params;
  const plan = await prisma.mealPlan.findUnique({ where: { id } });

  if (!plan || plan.userId !== session.user.id) {
    return new Response("Not found", { status: 404 });
  }

  const buffer = await buildPDF(plan.content, plan.title);
  const filename = `${plan.title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;

  return new Response(buffer as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
